import {PERMISSIONS} from 'react-native-permissions';

const AndroidPermissions = [
  PERMISSIONS.ANDROID.ACCESS_COARSE_LOCATION,
  PERMISSIONS.ANDROID.ACCESS_FINE_LOCATION,
  PERMISSIONS.ANDROID.POST_NOTIFICATIONS,
  PERMISSIONS.ANDROID.ACTIVITY_RECOGNITION,
];
export default AndroidPermissions;
