export const FONTS = {
  regular: 'Avenir-Regular',
  bold: 'Avenir-Heavy',
  light: 'Avenir-Light',
  medium: 'Avenir-Medium',
  semiBold: 'Avenir-Book',
  extraBold: 'Avenir-Black',
  italic: 'Avenir-Oblique',
  extraLight: 'Avenir-Light',
  extraBlack: 'Avenir-Black',
  boldItalic: 'Avenir-HeavyOblique',
  mediumItalic: 'Avenir-MediumOblique',
  semiBoldItalic: 'Avenir-BookOblique',
  extraBoldItalic: 'Avenir-BlackOblique',
  lightItalic: 'Avenir-LightOblique',
  ultraLight: 'Avenir-Light',
  barleyRegular: 'Barley-Regular',
};
